# Generated by Django 4.2.7 on 2025-11-07 06:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(help_text='Short description of the gallery image', max_length=200)),
                ('image', models.ImageField(help_text='Gallery photo', upload_to='gallery/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Room type name (e.g., 'Deluxe Room')", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL slug', unique=True)),
                ('description', models.TextField(help_text='Detailed room description including features')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per night in NPR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amenities', models.TextField(help_text='Comma-separated list of amenities (e.g., WiFi, AC, TV)')),
                ('image', models.ImageField(help_text='Room image', upload_to='rooms/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(help_text='Full name of the guest', max_length=100)),
                ('guest_email', models.EmailField(help_text='Email address of the guest', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('guest_phone', models.CharField(help_text='Phone number of the guest', max_length=20)),
                ('check_in', models.DateField(help_text='Check-in date')),
                ('check_out', models.DateField(help_text='Check-out date')),
                ('guests', models.IntegerField(help_text='Number of guests', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total booking amount in NPR', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='NPR', help_text='Currency code', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], default='pending', help_text='Current payment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(help_text='Room type being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
