# Generated by Django 4.2.7 on 2025-11-07 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_capacity',
            field=models.IntegerField(default=2, help_text='Maximum number of guests', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='room',
            name='size_sqft',
            field=models.IntegerField(default=200, help_text='Room size in square feet', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
