# Generated by Django 4.2.7 on 2025-11-07 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_room_max_capacity_room_size_sqft'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Hero slide title', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text="Optional subtitle (e.g., 'Blessed by Nature')", max_length=200)),
                ('description', models.TextField(help_text='Main description text for the hero slide')),
                ('image', models.ImageField(help_text='Background image for the hero slide', upload_to='hero/')),
                ('order', models.IntegerField(default=1, help_text='Display order (1-6)', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slide is displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['order'],
                'unique_together': {('order',)},
            },
        ),
    ]
