# Generated by Django 4.2.7 on 2025-11-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='visited_date',
            field=models.DateField(blank=True, help_text='Date when the guest visited the resort', null=True),
        ),
    ]
