# Generated by Django 4.2.7 on 2025-11-08 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_review_visited_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per night in EUR (auto-calculated or set manually)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='room',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per night in USD (auto-calculated or set manually)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
