# Generated by Django 4.2.7 on 2025-11-08 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_room_price_eur_room_price_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Room gallery photo', upload_to='rooms/gallery/')),
                ('caption', models.CharField(blank=True, help_text="Optional description (e.g., 'Main Bedroom', 'Bathroom', 'Living Area')", max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Set as the main image for this room')),
                ('order', models.IntegerField(default=0, help_text='Display order in gallery (lower numbers first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(help_text='The room this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.room')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
