# Generated by Django 4.2.7 on 2025-11-09 20:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_roomimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rooms', models.IntegerField(default=1, help_text='Total number of rooms of this type', validators=[django.core.validators.MinValueValidator(1)])),
                ('available_rooms', models.IntegerField(default=1, help_text='Currently available rooms (auto-calculated)', validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(help_text='Room type', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='main.room')),
            ],
            options={
                'verbose_name': 'Room Inventory',
                'verbose_name_plural': 'Room Inventory',
            },
        ),
    ]
