# Generated by Django 4.2.7 on 2025-11-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_roominventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO Description (150-160 chars). Leave empty to use excerpt.', max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO Keywords (comma-separated). Example: Nagarkot, Nepal, Resort, Hiking', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title (50-60 chars). Leave empty to use post title.', max_length=60),
        ),
    ]
