# Generated by Django 6.0.3 on 2026-03-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_blogpost_meta_description_blogpost_meta_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Diamond Hill Resort', help_text='About page title', max_length=200)),
                ('story', models.TextField(default='Diamond Hill Resort stands as a beacon of luxury and comfort in the heart of Nagarkot, Nepal...', help_text='Main story and background content for the About page')),
                ('values_intro', models.TextField(blank=True, help_text='Introduction text before the values section')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
