# Generated by Django 6.0.3 on 2026-03-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, help_text='Featured image for about section on homepage', null=True, upload_to='about/'),
        ),
    ]
